% call methods to make sure they exist and don't trigger syntax errors
function test_arm_api(arm_name)
    addpath('..')
    r = arm(arm_name)
    [p, t] = r.get_position_desired()
    [p, t] = r.get_position_local_desired()
    [p, v, e, t] = r.get_state_joint_current()
    [p, v, e, t] = r.get_state_joint_desired()
    [p, e, t] = r.get_state_joint_desired()
    [p, v, e, t] = r.get_state_joint_desired()
    [p, t] = r.get_position_current()
    [p, t] = r.get_position_local_current()
    [p, v, e, t] = r.get_state_joint_current()
    [v, t] = r.get_twist_body_current()
    [e, t] = r.get_wrench_current()
end
