function data_file_struct = collect_mtm_one_joint(config,...
                                                 mtm_arm,...
                                                 is_path_planning,...
                                                 is_collecting_data)
%  Institute: The Chinese University of Hong Kong
%  Author(s):  Hongbin LIN, Vincent Hui, Samuel Au
%  Created on: 2018-10-05

    % Collect Torque data by positive direction
    if config.is_pos_dir
        data_file_list = collect_mtm_one_joint_with_one_dir(config,...
                                                              mtm_arm,...
                                                              config.pos_joint_range_list,...
                                                              config.pos_data_path,...
                                                              is_path_planning,...
                                                              is_collecting_data,...
                                                              'positive');
        data_file_struct.pos = data_file_list;
    end
    if config.is_neg_dir
        data_file_list = collect_mtm_one_joint_with_one_dir(config,...
                                                              mtm_arm,...
                                                              config.neg_joint_range_list,...
                                                              config.neg_data_path,...
                                                              is_path_planning,...
                                                              is_collecting_data,...
                                                              'negative');
        data_file_struct.neg = data_file_list;
    end
end

