function [is_lse_finish, output_dynamic_matrix] = LSE_MTM_one_joint(config_lse_joint, previous_config)
%  Institute: The Chinese University of Hong Kong
%  Author(s):  Hongbin LIN, Vincent Hui, Samuel Au
%  Created on: 2018-10-05

    % General Setting
    is_lse_finish  = false;
    output_dynamic_matrix = zeros(41,2);

    if ~exist('previous_config')
        disp(sprintf('LSE of Joint%d by positive direction has start..',config_lse_joint.Joint_No));
               [is_pos_lse_success, pos_dynamic_param] = LSE_Model(config_lse_joint.Joint_No,... 
                    config_lse_joint.std_filter,...
                    config_lse_joint.g_constant,...
                    config_lse_joint.Is_Plot,...
                    config_lse_joint.issave_figure,...
                    config_lse_joint.input_pos_data_path,...            
                    config_lse_joint.input_pos_data_files,...
                    config_lse_joint.output_pos_param_path,...
                    config_lse_joint.output_pos_fig_path,...
                    config_lse_joint.prior_param_index,...
                    config_lse_joint.prior_param_values,...
                    config_lse_joint.Output_Param_Joint_No);
        if(is_pos_lse_success)
        disp(sprintf('LSE of Joint%d by negative direction has start..',config_lse_joint.Joint_No));
               [is_neg_lse_success, neg_dynamic_param] = LSE_Model(config_lse_joint.Joint_No,... 
                    config_lse_joint.std_filter,...
                    config_lse_joint.g_constant,...
                    config_lse_joint.Is_Plot,...
                    config_lse_joint.issave_figure,...
                    config_lse_joint.input_neg_data_path,...            
                    config_lse_joint.input_neg_data_files,...
                    config_lse_joint.output_neg_param_path,...
                    config_lse_joint.output_neg_fig_path,...
                    config_lse_joint.prior_param_index,...
                    config_lse_joint.prior_param_values,...
                    config_lse_joint.Output_Param_Joint_No);
        else
            return
        end

     
    else
        disp(sprintf('LSE of Joint%d by positive direction has start..',config_lse_joint.Joint_No));
              [is_pos_lse_success, pos_dynamic_param] = LSE_Model(config_lse_joint.Joint_No,...
                    config_lse_joint.std_filter,...
                    config_lse_joint.g_constant,...
                    config_lse_joint.Is_Plot,...
                    config_lse_joint.issave_figure,...
                    config_lse_joint.input_pos_data_path,...            
                    config_lse_joint.input_pos_data_files,...
                    config_lse_joint.output_pos_param_path,...
                    config_lse_joint.output_pos_fig_path,...
                    config_lse_joint.prior_param_index,...
                    config_lse_joint.prior_param_values,...
                    config_lse_joint.Output_Param_Joint_No,...
                    previous_config.output_pos_param_path); 
       if(is_pos_lse_success)       
           disp(sprintf('LSE of Joint%d by negative direction has start..',config_lse_joint.Joint_No));
                     [is_neg_lse_success, neg_dynamic_param] = LSE_Model(config_lse_joint.Joint_No,... 
                        config_lse_joint.std_filter,...
                        config_lse_joint.g_constant,...
                        config_lse_joint.Is_Plot,...
                        config_lse_joint.issave_figure,...
                        config_lse_joint.input_neg_data_path,...            
                        config_lse_joint.input_neg_data_files,...
                        config_lse_joint.output_neg_param_path,...
                        config_lse_joint.output_neg_fig_path,...
                        config_lse_joint.prior_param_index,...
                        config_lse_joint.prior_param_values,...
                        config_lse_joint.Output_Param_Joint_No,....
                        previous_config.output_neg_param_path);  
       end
    end
    
    if is_pos_lse_success & is_neg_lse_success
        disp(sprintf('Least Square Estimation of Joint%d has finished!',config_lse_joint.Joint_No));
        disp(sprintf(''));
        is_lse_finish = true;
        output_dynamic_matrix = [pos_dynamic_param, neg_dynamic_param];
    end
    
end  

