#!/usr/bin/env python

import sys

from rqt_gui.main import Main
from rqt_dvrk.dvrk_dashboard import dvrkDashboard

plugin = 'rqt_dvrk'
main = Main(filename=plugin)
sys.exit(main.main(standalone=plugin))
